### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by choing98** [devaspirant0510/WordMaster#28]
- [x] Chip,ChipGroup
- [x] 단어 상세화면
- [ ] 데이터바인딩 뷰모델
- [x] Util 함수에서 SharedPreference 관리
- [x] 깃허브 커밋로그 구현
- [x] 검색화면에서 단어 다운로드 기능 구현
- [ ] 내부디비 구현
- [ ] 브로드캐스트리시버로 네트워크 연결상태 확인
- [x] 구글로그인 구현
- [x] 유저가입시 저장되는 정보 변경
- [ ] 유저 프로필사진 업로드 구현
